export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  BATTLE_SCENE: 'BATTLE_SCENE',
  BATTLE_SCENE_1: 'BATTLE_SCENE_1',
  WORLD_SCENE: 'WORLD_SCENE',
  FLOORONE_BACKGROUND: 'FLOORONE_BACKGROUND',
  FLOORTWO_BACKGROUND: 'FLOORTWO_BACKGROUND',
  TILE_SCENE: 'TILE_SCENE',
});
